#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: barretlee
disqus_show_comment_count: true

# site
title: swinghu's Blog
url: http://swinghu.github.com
repo: http://qianduannotes.duapp.com/github/swinghu.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: Barret Lee
author_email: barret.china@gmail.com
author_info: <a href="http://barretlee.com">BarretLee</a>
