#
# Blog Settings
#


# Jekyll Settings
markdown: rdiscount
pygments: true
paginate: 6
paginate_path: /page:num
permalink: /:title
baseurl: /
#lsi: true

# Disqus Comments
disqus_short_name: swinghu
disqus_show_comment_count: true

# site
title: swinghu's Blog
url: http://swinghu.github.io
repo: http://qianduannotes.duapp.com/github/barretlee.github.com
feed: /atom.xml

# color scheme
highlight: light

# author
author_name: swing hu
author_email: ogrecpp@gmail.com
author_info: <a href="http://swinghu.github.io">swinghu</a>
